SIZES = {"h": 2, "H": 2, "?": 1, "b": 1, "B": 1}

CMD = {
   "Start": 128,
   "Baud": 129,
   "Safe": 131,
   "Full": 132,
   "Power": 133,
   "Spot": 134,
   "Clean": 135,
   "Max": 136,
   "Drive": 137,
   "Moters": 138,
   "LEDs": 139,
   "Song": 140,
   "Play": 141,
   "Sensors": 142,
   "Seek Dock": 143,
   "PWM Moters": 144,
   "Drive Direct": 145,
   "Drive PWM": 146,
   "Stream": 148,
   "Query List": 149,
   "Pause/Resume Stream": 150,
   "Scheduling LEDs": 162,
   "Digit LEDs Raw": 163,
   "Digit LEDs ASCII": 164,
   "Buttons": 165,
}

PARAMS = {
    "STRAIGHT_RADIUS": 32768,
    "MIN_RADIUS": -2000,
    "MAX_RADIUS": 2000,
    "MIN_VELOCITY": -500,
    "MAX_VELOCITY": 500,
}

SENSORS = {
    "Bumps Wheeldrops": [7, "B"],
    "Wall": [8, "?"],
    "Cliff Left": [9, "?"],
    "Cliff Front Left": [10, "?"],
    "Cliff Front Right": [11, "?"],
    "Cliff Right": [12, "?"],
    "Virtual Wall": [13, "?"],
    "Overcurrents": [14, "B"],
    "Dirt Detect": [15, "B"],
    "Unused 1": [16, "B"],
    "Ir Opcode": [1, "B"],
    "Buttons": [18, "B"],
    "Distance": [19, "h"],
    "Angle": [20, "h"],
    "Charging State": [21, "B"],
    "Voltage": [22, "H"],
    "Current": [23, "h"],
    "Temperature": [24, "b"],
    "Battery Charge": [25, "H"],
    "Battery Capacity": [26, "H"],
    "Wall Signal": [27, "H"],
    "Cliff Left Signal": [28, "H"],
    "Cliff Front Left Signal": [29, "H"],
    "Cliff Front Right Signal": [30, "H"],
    "Cliff Right Signal": [31, "H"],
    "Unused 2": [32, "B"],
    "Unused 3": [33, "H"],
    "Charger Available": [34, "b"],
    "Open Interface Mode": [35, "b"],
    "Song Number": [36, "b"],
    "Song Playing?": [37, "b"],
    "Oi Stream Num Packets": [38, "b"],
    "Velocity": [39, "h"],
    "Radius": [40, "h"],
    "Velocity Right": [41, "h"],
    "Velocity Left": [42, "h"],
    "Encoder Counts Left": [43, "H"],
    "Encoder Counts Right": [44, "H"],
    "Light Bumper": [45, "B"],
    "Light Bump Left": [46, "H"],
    "Light Bump Front Left": [47, "H"],
    "Light Bump Center Left": [48, "H"],
    "Light Bump Center Right": [49, "H"],
    "Light Bump Front Right": [50, "H"],
    "Light Bump Right": [51, "H"],
    "Ir Opcode Left": [52, "B"],
    "Ir Opcode Right": [53, "B"],
    "Left Motor Current": [54, "h"],
    "Right Motor Current": [55, "h"],
    "Main Brush Current": [56, "h"],
    "Side Brush current": [57, "h"],
    "Stasis": [58, "?"]
}
